[package]
name = "snake_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.0"
bevy_ascii_terminal = "0.14.0"
bevy_framepace = "0.15.0"

[profile.dev.package."*"]
opt-level = 3
